mybatis-plus:
  mapper-locations: classpath*:com/yangye/meetingfilms/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0 数据库自增   1:用户输入id  2:全局唯一ID(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudstudy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    filters: log4j,wall,mergeStat
    druid:
      password: 095261
      username: root


logging:
  config: classpath:logback.xml
